game = Mancala()
player1 = game.create_player("Lily")
player2 = game.create_player("Lucy")
print(game.play_game(1, 3))
game.play_game(1, 1)
game.play_game(2, 3)
game.play_game(2, 4)
game.play_game(1, 2)
game.play_game(2, 2)
game.play_game(1, 1)
game.print_board()
print(game.return_winner())


game = Mancala()
player1 = game.create_player("Lily")
player2 = game.create_player("Lucy")
game.print_board()
print(game.play_game(1, 1))
game.print_board()



game = Mancala()
player1 = game.create_player("Lily")
player2 = game.create_player("Lucy")
game.play_game(1, 1)
game.play_game(1, 2)
game.play_game(1, 3)
game.play_game(1, 4)
game.play_game(1, 5)
game.play_game(1, 6)
game.print_board()
print(game.return_winner())
